V.o.encoding = "UTF-8"
V.o.mouse = "a"
V.o.splitbelow = true
V.o.cmdheight = 1
V.o.updatetime = 750
V.o.colorcolumn = "80"
V.o.tabstop=4
V.o.expandtab = true
V.o.shiftwidth=4
V.o.laststatus=2
V.o.showmode = false
V.o.showmatch = true
V.o.ignorecase = true
V.o.incsearch = true
V.o.autoread = true
