#!/usr/bin/env bash
# Use a YubiKey (FIDO2/U2F) to authenticate `sudo`: tap the key *instead of*
# typing your password. Falls back to the password if the key is absent or the
# tap fails, so you never get locked out (the PAM line is `sufficient`, not
# `required`).
#
# Unlike install-oomd-tuning.sh this doesn't symlink a committed config:
#   - the key registration (~/.config/Yubico/u2f_keys) is generated by tapping
#     the physical key and is per-key, so it's not worth committing; and
#   - the PAM change is a single line inserted idempotently into the
#     package-owned /etc/pam.d/sudo rather than replacing the whole file.
#
# Re-runnable. Pass --add-key to register another key into an existing setup.
set -euo pipefail

PAM_FILE="/etc/pam.d/sudo"
AUTHFILE="${XDG_CONFIG_HOME:-$HOME/.config}/Yubico/u2f_keys"
MARKER="# yubikey-sudo (managed by install-yubikey-sudo.sh)"
# `cue`       -> print "touch your key" prompt
# `openasuser`-> read the authfile as the invoking user (it lives in ~/.config)
PAM_LINE="auth   sufficient   pam_u2f.so   cue openasuser"

ADD_KEY=0
[[ "${1:-}" == "--add-key" ]] && ADD_KEY=1

# --- 1. module --------------------------------------------------------------
if ! dpkg -s libpam-u2f >/dev/null 2>&1; then
  echo "Installing libpam-u2f ..."
  sudo apt-get update -qq
  sudo apt-get install -y libpam-u2f
fi

# --- 2. register the key (interactive: the key will blink — tap it) ---------
register_key() {
  echo "Insert your YubiKey and tap it when it blinks ..."
  mkdir -p "$(dirname "$AUTHFILE")"
  # pamu2fcfg emits one line per key; append so multiple keys accumulate.
  pamu2fcfg >> "$AUTHFILE"
  chmod 600 "$AUTHFILE"
  echo "Registered. $AUTHFILE now has $(wc -l < "$AUTHFILE") key(s)."
}

if [[ "$ADD_KEY" == 1 ]]; then
  register_key
elif [[ ! -s "$AUTHFILE" ]]; then
  register_key
  echo
  echo ">> Strongly recommended: register a BACKUP key now so a lost key can't"
  echo ">> lock you out. Re-run:  $0 --add-key"
else
  echo "Key registration already present ($AUTHFILE); skipping."
  echo "(Run '$0 --add-key' to add another key.)"
fi

# --- 3. patch /etc/pam.d/sudo (idempotent, before @include common-auth) -----
if sudo grep -qF "$MARKER" "$PAM_FILE"; then
  echo "PAM already configured in $PAM_FILE; skipping."
else
  sudo cp -a "$PAM_FILE" "$PAM_FILE.bak.$(date +%Y%m%d%H%M%S)"
  # Insert our two lines immediately before the first `@include common-auth`
  # so the U2F check runs before the password stack.
  sudo awk -v marker="$MARKER" -v line="$PAM_LINE" '
    !done && /@include[[:space:]]+common-auth/ {
      print marker; print line; done=1
    }
    { print }
    END { if (!done) exit 3 }
  ' "$PAM_FILE" | sudo tee "$PAM_FILE.new" >/dev/null || {
    echo "ERROR: no '@include common-auth' line found in $PAM_FILE; not modified." >&2
    sudo rm -f "$PAM_FILE.new"
    exit 1
  }
  sudo mv "$PAM_FILE.new" "$PAM_FILE"
  echo "Patched $PAM_FILE (backup saved alongside)."
fi

# --- 4. show result + how to test safely ------------------------------------
echo
echo "== auth lines in $PAM_FILE =="
sudo grep -nE 'pam_u2f|common-auth' "$PAM_FILE"
cat <<'EOF'

Test WITHOUT risking a lockout — keep this shell privileged first:

    sudo -v                       # refresh creds in THIS shell
    # then in a SECOND terminal:
    sudo -k && sudo echo works    # should prompt you to tap the key

If the tap fails it falls back to your password, and you can fix
/etc/pam.d/sudo from the still-privileged first shell.
EOF
