# sudo, YubiKey, polkit.
{ config, lib, pkgs, ... }:

{
  # --- YubiKey for sudo ------------------------------------------------------
  # Declarative replacement for scripts/install-yubikey-sudo.sh's PAM surgery
  # (that script inserted `auth sufficient pam_u2f.so cue openasuser` into
  # /etc/pam.d/sudo by hand — on NixOS /etc/pam.d is generated, so hand-editing
  # would be reverted on the next rebuild).
  #
  # `control = "sufficient"` keeps the password as a fallback: no key, no
  # lockout. The key *registration* is still imperative and stays that way — it
  # is generated by tapping the physical key, is per-key, and isn't worth
  # committing:
  #
  #   mkdir -p ~/.config/Yubico
  #   pamu2fcfg >> ~/.config/Yubico/u2f_keys     # tap when it blinks
  #   pamu2fcfg >> ~/.config/Yubico/u2f_keys     # …and a BACKUP key
  #
  # Test without risking a lockout: `sudo -v` in this shell, then from a second
  # terminal `sudo -k && sudo echo works`.
  security.pam.u2f = {
    enable = true;
    control = "sufficient";
    settings = {
      cue = true; # print "touch your key"
      # the authfile lives in ~/.config, so read it as the invoking user
      openasuser = true;
    };
  };
  security.pam.services.sudo.u2fAuth = true;

  # pcscd is only needed for PIV/smartcard use, not FIDO2 — left off. Add
  # `services.pcscd.enable = true;` if you start using the YubiKey for GPG.
  services.udev.packages = [ pkgs.yubikey-personalization ];

  security.sudo = {
    enable = true;
    # Timestamp is per-tty by default on NixOS; keep sudo's cached creds for a
    # sensible while so a YubiKey tap isn't demanded per command in a script.
    extraConfig = ''
      Defaults timestamp_timeout=15
    '';
  };

  # `sugit`/`suvim` aliases (zsh/alias.zsh) run `sudo -E`, which needs env
  # preservation to be permitted for the vars they care about.
  security.polkit.enable = true;

  # No SSH server, matching the current machine (docs/claude-code-from-phone.md
  # is the plan if that changes). Explicit so it can't be enabled by accident by
  # some other module's default.
  services.openssh.enable = false;
}
